In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('/kaggle/input/datasets/gpiosenka/sports-classification/sports.csv')

       class id                    filepaths           labels data set
0             0     train/air hockey/001.jpg       air hockey    train
1             0     train/air hockey/002.jpg       air hockey    train
2             0     train/air hockey/003.jpg       air hockey    train
3             0     train/air hockey/004.jpg       air hockey    train
4             0     train/air hockey/005.jpg       air hockey    train
...         ...                          ...              ...      ...
14488        99  valid/wingsuit flying/1.jpg  wingsuit flying    valid
14489        99  valid/wingsuit flying/2.jpg  wingsuit flying    valid
14490        99  valid/wingsuit flying/3.jpg  wingsuit flying    valid
14491        99  valid/wingsuit flying/4.jpg  wingsuit flying    valid
14492        99  valid/wingsuit flying/5.jpg  wingsuit flying    valid

[14493 rows x 4 columns]

In [6]:
df.head()

   class id                 filepaths      labels data set
0         0  train/air hockey/001.jpg  air hockey    train
1         0  train/air hockey/002.jpg  air hockey    train
2         0  train/air hockey/003.jpg  air hockey    train
3         0  train/air hockey/004.jpg  air hockey    train
4         0  train/air hockey/005.jpg  air hockey    train